//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lastai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lastaiTable
    {
        public int id { get; set; }
        public string Picture { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public string Born { get; set; }
        public string Quote { get; set; }
        public string Profession { get; set; }
        public string Title { get; set; }
        public string Short_Description { get; set; }
        public string Long_Description { get; set; }
        public string Comment { get; set; }
    }
}
